/**
 * `docs/promotion-readiness.md`, rendered from the verdict and the proposal.
 *
 * The prose around the verdict is fixed text in this template; every statement that could differ
 * between two runs — met or not, what each finding says, what is proposed and what is excluded —
 * comes from the verdict or the proposal. A sentence nobody can make disagree with the artefacts is
 * the only kind this document is allowed to contain.
 */

import { PROPOSAL_PATH, type Proposal } from "./proposal.js";
import type { ItemVerdict, Verdict } from "./verdict.js";

export const READINESS_PATH = "docs/promotion-readiness.md";

const HEADER =
  "<!-- Generated by `pnpm readiness` from the published artefacts. Do not edit by hand: " +
  "`pnpm readiness:check` fails when this file disagrees with them. -->";

function statusWord(item: ItemVerdict): string {
  return item.met ? "**Met**" : "**Not met**";
}

function itemSection(item: ItemVerdict): string {
  const lines = [
    `### ${String(item.item)}. ${item.title} — ${item.met ? "met" : "not met"}`,
    "",
    ...item.findings.map(
      (finding) => `- ${finding.holds ? "Holds" : "**Fails**"}: ${finding.text}.`,
    ),
    "",
    `Decided from ${item.sources.map((source) => `\`${source}\``).join(", ")}.`,
  ];
  return lines.join("\n");
}

function proposalSection(proposal: Proposal): string {
  const changes = proposal.changes;
  const lines = [
    "## The proposal",
    "",
    `Because all seven items hold, \`pnpm readiness\` wrote \`${PROPOSAL_PATH}\`: every field PRD 12`,
    "lists, with the value the artefacts support. **It is a file for review, and nothing has been",
    "promoted.** The manifest is a reviewed edit in the portfolio repository, which this repository",
    "never writes; until that edit is made, `proofLevel` is still `code`.",
    "",
    "| Field | Proposed |",
    "| --- | --- |",
    `| \`status\` | \`${changes.status}\` |`,
    `| \`proofLevel\` | \`${changes.proofLevel}\` |`,
    `| \`content.problem\` | from PRD section 1, ${String(changes.content.problem.length)} characters |`,
    `| \`content.limitations\` | ${String(changes.content.limitations.length)} entries from \`docs/limitations.md\` |`,
    `| \`stack\` | ${Object.entries(changes.stack)
      .filter(([, terms]) => terms.length > 0)
      .map(([group, terms]) => `${group}: ${terms.join(", ")}`)
      .join("; ")} |`,
    `| \`metrics\` | ${String(changes.metrics.length)}, each with \`environment\`, \`sampleSize\`, \`synthetic: true\`, \`measuredAt\` and \`evidenceUrl\` |`,
    `| \`evidence\` | ${String(changes.evidence.length)}, primary: \`${changes.evidence.find((entry) => entry.primary)?.id ?? "none"}\` |`,
    `| \`dates.started\` | ${changes.dates.started === null ? "not read" : `\`${changes.dates.started}\``} |`,
    `| \`dates.lastVerified\` | \`${changes.dates.lastVerified}\` |`,
    "| `integrity.reviewedBy` | left for the reviewer |",
    "",
    "Proposed metrics, each value copied unrounded from the artefact named in the proposal's",
    "`provenance`:",
    "",
    "| Metric | Value | Unit | Sample size |",
    "| --- | --- | --- | --- |",
    ...changes.metrics.map(
      (metric) =>
        `| ${metric.label} | ${String(metric.value)} | ${metric.unit} | ${String(metric.sampleSize)} |`,
    ),
    "",
    "Left out, each for a stated reason:",
    "",
    ...proposal.excluded.map((entry) => `- ${entry.what} — ${entry.reason}.`),
    "",
    "For the reviewer:",
    "",
    ...proposal.forTheReviewer.map((note) => `- ${note}`),
  ];
  return lines.join("\n");
}

function refusalSection(verdict: Verdict): string {
  const unmet = verdict.items.filter((item) => !item.met);
  return [
    "## The refusal",
    "",
    `No manifest edit is proposed. PRD 12: "Until every item is present, the manifest stays at`,
    '`code`, and no number from section 4.5, 8, or 9.3 may be restated anywhere as an achievement."',
    `Item(s) ${unmet.map((item) => String(item.item)).join(", ")} ${unmet.length === 1 ? "does" : "do"} not hold; the failing findings above say why.`,
    `\`pnpm readiness\` removes \`${PROPOSAL_PATH}\` when it refuses, so a proposal from an earlier`,
    "verdict cannot outlive the verdict that justified it.",
  ].join("\n");
}

export function renderReadiness(verdict: Verdict, proposal: Proposal | null): string {
  const met = verdict.items.filter((item) => item.met).length;
  const headline = verdict.allMet
    ? `**Verdict: all seven PRD 12 items are met. A manifest edit is proposed for review; nothing has been promoted, and the manifest stays at \`proofLevel: "code"\` until a person makes that edit.**`
    : `**Verdict: not ready. ${String(met)} of seven PRD 12 items are met, and the manifest stays at \`proofLevel: "code"\`.**`;

  const sections = [
    HEADER,
    "",
    "# Promotion readiness",
    "",
    headline,
    "",
    "PRD 12 lists seven artefacts that must exist before the manifest may move from `code` to",
    "`measured`. Each verdict below is computed by `tools/readiness` from the file that is supposed to",
    "satisfy the item — fields present, counts consistent across files, references that resolve — and",
    "every finding it made is listed, including the ones that hold. Until P18c this document was",
    "written by hand, and it went stale the way hand-written verdicts do.",
    "",
    "A met item is a statement about what an artefact contains. It is not a statement that the",
    "numbers in it are good; several are not, and the limitations list and the notes for the reviewer",
    "say which.",
    "",
    "## The seven items",
    "",
    "| # | Artefact | Verdict |",
    "| --- | --- | --- |",
    ...verdict.items.map(
      (item) => `| ${String(item.item)} | ${item.title} | ${statusWord(item)} |`,
    ),
    "",
    ...verdict.items.flatMap((item) => [itemSection(item), ""]),
    proposal === null ? refusalSection(verdict) : proposalSection(proposal),
    "",
    "## What this verdict cannot decide",
    "",
    "- **Whether to promote.** That is a person's reviewed edit to the portfolio manifest. This",
    "  repository proposes; it never writes `content/projects/RAG-01.json`.",
    "- **Whether the artefacts are true.** The checks establish that each artefact contains what",
    "  PRD 12 names and agrees with the others. The commit, the corpus hash and the raw per-query and",
    "  per-span files are what let somebody re-run the evaluation and the load run and compare.",
    "- **External validation.** Promotion beyond `measured` needs an evidence item with",
    "  `external: true`, and nothing in this project's scope produces one.",
    "",
    "## Reproducing this",
    "",
    "```bash",
    "pnpm readiness         # decide, rewrite this file, write or remove the proposal",
    "pnpm readiness:check   # fail if this file or the proposal disagrees with the artefacts",
    "```",
    "",
  ];
  return sections.join("\n");
}
